name: Run Bot (24 Hours)

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */5 * * *'

concurrency:
  group: fjrtelebot
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.TOKEN }}
      PRIVATE: ${{ secrets.PRIVATE }}
      GC: ${{ secrets.GC }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      diioffc: ${{ secrets.diioffc }}
      archive: ${{ secrets.archive }}
      vreden: ${{ secrets.vreden }}
      vapis: ${{ secrets.vapis }}
      myquran: ${{ secrets.myquran }}
      siputzx: ${{ secrets.siputzx }}
      waifuim: ${{ secrets.waifuim }}
      waifupics: ${{ secrets.waifupics }}

    steps:
      - name: Setup & Install
        run: |
          # Checkout repository
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY .
          
          # Setup Node.js (manual pakai nvm biar satu blok aja)
          curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install 22
          
          # Setup FFmpeg
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          
          # Install pnpm
          npm install -g pnpm
          
          # Install dependencies
          pnpm install
          
          # Install yt-dlp (binary)
          sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp
          yt-dlp --version

      - name: Run bot for 6h
        run: |
          timeout 6h pnpm run start
