name: Test yt-dlp Binary

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-yt-dlp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install yt-dlp (binary)
        run: |
          sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp

      - name: Check yt-dlp version
        run: yt-dlp --version
